#App
server.port=8080
spring.application.name=project-base

#DATABASE
#DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/StudyDate
spring.datasource.username=Local_Data
spring.datasource.password=123456
#JPA / HIBERNATE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#JWT
jwt.secret=9A3F48B2C7E5D184F60A3B5C9E2D87F14A5B8C3D6E9F20B4C7D5E8F1A2B3C4D5
#Expiration time (minutes)
jwt.access.expiration_time=60
jwt.refresh.expiration_time=1440

#Cloudinary
cloudinary.cloud_name=
cloudinary.api_key=
cloudinary.api_secret=

#Mail
mail.username=
mail.password=

#Swagger
springdoc.api-docs.enabled=true
springdoc.packagesToScan=org.hit.chiikaiwabe.controller
springdoc.pathsToMatch=/**

#Info Admin
admin.username=adminkien
admin.password=admin
admin.lastName=Kien
admin.firstName=Nguyen