#App
server.port=${PORT:8080}
spring.application.name=project-base
spring.config.import=optional:file:.env[.properties]

#DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/StudyDate
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#JPA / HIBERNATE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#JWT
jwt.secret=${JWT_SECRET}

#Expiration time (minutes)
jwt.access.expiration_time=30
jwt.refresh.expiration_time=10080

#Cloudinary
cloudinary.cloud_name=${CLOUD_NAME}
cloudinary.api_key=${CLOUD_API_KEY}
cloudinary.api_secret=${CLOUD_API_SECRET}

# Brevo API (used instead of SMTP on Render)
brevo.api-key=${BREVO_API_KEY}
brevo.sender-email=${BREVO_SENDER_EMAIL}
brevo.sender-name=${BREVO_NAME}

#Swagger
springdoc.api-docs.enabled=true
springdoc.packagesToScan=org.hit.chiikaiwabe.controller
springdoc.pathsToMatch=/**

#Info Admin
admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}
admin.lastName=${ADMIN_LASTNAME}
admin.firstName=${ADMIN_FIRSTNAME}

#Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

#Radar
radar.default-radius-km=${DEAFULT_RADIUS_KM}
radar.max-radius-km=${MAX_RADIUS_KM}
radar.ttl-minutes=${TTL_MINUTES}

#Multipart File Upload Limits
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
#Firebase
firebase.config-path=${FIREBASE_CONFIG_PATH}
#WebSocket
spring.websocket.stomp.buffer-size=8192


#Chat
chat.max-group-members=30
chat.max-file-size-mb=10
chat.recall-timeout-minutes=30
